### PR TITLE
Add help patches for interactive components

### PR DESCRIPTION
**Pull request by geofholbrook**
Just made a start at this. If this is a good approach, I'll continue with it: A single file called interactive.opat, which has a sub patch for each component (I made one for SWITCH).

I think it makes sense to include reactive mode in these patches... reactive + interactive seems like a good use case, despite your cautionary language in the paper about becoming too "Max-like"!

### CODE REVIEW

**Comment by j-bresson** [comment]
Nice that you are starting this. Interactive boxes are the nex on my list for the documentation pages, and it would be nice if it comes along with a few help patches.
I prefer a set of "flat" patches in a new "Interactive boxes" folder, rather than a single patch containing sub-patches, because I find it more accessible / easier to read, browse etc. but also because there is a feature that automatically searches for and opens the help patch of a box (see in the Help menu) — and so the help patch just need to have the same name as the box (switch.opat, slider.opat, button.opat, ...).

**Comment by j-bresson** [comment]
And yes, these boxes are definitely meant to be used with the reactive mode.

**Comment by j-bresson** [comment]
In the `switch` example, it would probably make sense to add a `chord` box after the `switch`, so we see that one of the chords was selected. Otherwise it may seem odd thqt the output data be processed through first (therefore as a list) considering your comment about the result being a list in case of multiple-selection...

**Comment by j-bresson** [comment]
You should try to rebase this branch on the current `master`.

**Comment by geofholbrook** [comment]
concerning rebasing ... when I try that (git rebase upstream/master) it claims to be up to date. Do you see a problem?

**Comment by j-bresson** [comment]
> Do you see a problem? 

It's just becaue your first three commiuts from previous PRs got swallowed into `origin/master` when I rebased it, so your own `master` now diverges from it. You could also just pull `origin/master`, probably. I think this would also get fixed when merging the PR anyway.

**Comment by geofholbrook** [comment]
I see that the history is subtly different between my master and the main repo master (the commit messages' first character is capital and the hashes are different, and strangely _my_ master includes this: "Merge pull request cac-t-u-s#132 from geofholbrook/fix/show-markers", which is absent from the main repo.

Trouble is `git diff master upstream/master` (note that my `upstream/master` is your `origin/master`) yields nothing ... all the files are the same. So it doesn't want to rebase ... not to either master or docs/interactive. Maybe you know a trick! Basically we want to make the histories match, correct?

**Comment by j-bresson** [comment]
When I rebased master the "Merge pull request..." disappeared because its contents was basically what was in the commits of the merged branch (which were integrated in `master`). This is a wrong manip of mine, somehow. And yes, after I did it I fixed the case of the first message word as well. Still, you should be able to rebase on this. 🤔

**Comment by j-bresson** [comment]
ok, I just did the rebased and force-pushed it on your branch (seems like I have write permission on it:).

**Comment by geofholbrook** [comment]
Hey presto! Whatever you did seems to have had the desired effect. I think I've followed your example (the workflow rebase + force-push) to properly sync my local feature branch, local master, and remote master with the main repo.

I guess once I invite you to pull from my fork, github gives you write access! Fair enough :)

pssst ... see #139, it might help me with this branch.

**Comment by j-bresson** [comment]
> pssst ... see #139, it might help me with this branch.

Yes, I've seen that and will look into it. Sorry I'm a little bit slow with following-up everything :)

**Comment by j-bresson** [comment]
I think #139 is "solved" now.

**Comment by geofholbrook** [comment]
close to competed these help patches, except list-menu could be updated if we address #155

**Comment by j-bresson** [comment]
Nice 👍 
I can try to work on these `list-menu` updates tonight.
Eventually I think you can just squash every help-patch created in a single commit.

**Comment by JulianAvilaS** [comment]
Dear Jean. Nice work with OM-sharp!!!! I wonder if it is possible to use the Tristan library with OM-sharp. It is very useful for students when they are studying spectral techniques. ¿Is that possible? Thank you for your time.

**Comment by j-bresson** [comment]
@JulianAvilaS I'm moving thsi to a thread in cac-t-u-s/om-sharp-users#10
This is a pull request about help-patches and really not the place to discuss this 😄

**Comment by j-bresson** [comment]
Hey @geofholbrook, I was wondering what is the status of this branch. 
I will release v1.1 soon and was wondering if we could include that in it... ?
Let me know!

**Comment by geofholbrook** [comment]
Hi Jean,
  I just had a look at these help patches. Made a couple of adjustments. I had gone through a few iterations for the button patch "advanced usage" subpatcher, which was related to our discussion of the 'mem' box. In the end I followed one of your suggested which was to use the accum box instead for this purpose. 
  Anyway it seems to be complete ... there are 6 help patches for the 6 interactive boxes, and they all seem to work and demonstrate the utility of each fairly well. Let me know if you have any requests!

**Comment by j-bresson** [comment]
Ok, great. Looking at it now.

**Comment by j-bresson** [comment]
Seems like something went wrong with rebasing the branch.. 🤔 Why does the PR include all these commits from `master` ?

**Comment by j-bresson** [comment]
I can't interactive-rebase it either: falling on pretty important conflicts in the .opat files — seems over my git-conflict resolution skills :(

**Comment by j-bresson** [comment]
Btw. you should feel free to interactively rebase and cleanup your branch while it is not yet merged: for instance if you create a file and remove it right after (e.g. interactive.opat in the first couple of commits), these can probably be squashed and we never hear about this temporary file again! 
Also, since diffs are not so easy to process with patch files (and we will probably never need to dig out and reverse any specific change in it, etc.), I guess it would be fine if the branch ends up with just one commit for each help-patch file added, or for each "major" upgrade of it.

**Comment by geofholbrook** [comment]
Well, if it got messed up, maybe I could just start over? New branch, and I'll copy the help-patches in and make a single commit in? New pull request?

**Comment by j-bresson** [comment]
As you like, but I guess it can all just be cleaned up here as well. I managed to rebase it locally now, so if you want I can just push your branch and we can continue from there.

**Comment by geofholbrook** [comment]
Sure, do that!

**Comment by j-bresson** [comment]
Ok, I've pushed a rebased version and a couple of additional commits. I have a few tricks that I applied to make the patches look simpler, somehow (avoid unnecessary zig-zag and connection crossing, align boxes, etc.). (Note that teh SHIFT-A command is a goof friend to start with aligning boxes and connections). Replaced prints by value boxes at a few places, etc.
A little bit more changes in the `button` patch, as explained in the commit message.

**Comment by geofholbrook** [comment]
Jean, can we do something to prevent git from attempting to merge .opat files? Because otherwise it seems there are always merge conflicts when I pull to my local repo. Easy to resolve (just accept all incoming changes) but then there's a merge commit that shouldn't be there. Can we make a .gitattributes with:
```*.opat merge=keepTheirs```  
and put it in the root or in the help-patches folder?

**Comment by geofholbrook** [comment]
I get a lot of wrongly formatted comments (labels and titles), I guess because of the font size in my preferences. Is it correct for the font size for comments to be set by the user preferences, rather than the patch file?
busted-comments

**Comment by j-bresson** [comment]
> Jean, can we do something to prevent git from attempting to merge .opat files?

I don't know :(

> there are always merge conflicts when I pull to my local repo.

Yeah, this  is not surprising that there are merge conflicts, sinec I rebased and force-pushed on the branch. 
I gues sin that case what we should do is a `reset --hard` before top pull... 🤔

**Comment by j-bresson** [comment]
> I get a lot of wrongly formatted comments

Mhh.. interesting I thought my recent changes on comment sizes would have fixed that.
What's your Preference's comment font ?

**Comment by j-bresson** [comment]
Alright, no the problem with comments is actually the intended effect of my recent changes: increase the height of the comment box when the contents doesn't fit. So the problem is that I adjusted the comment width to my font size, and so it breaks it into two lines now with your wider font.

I don't think I should necessarily change that but there is here something to think about this font preference. => Shall it apply just at creating the patch, and then be a property of the box ? That would fix this kind of problem, but prevent from global settings (like, changing the preference changes the font of all the comments that follow font preferences).

In the meantime, I think shared patches (and helps patches should preferably contain fixed-font comments (=> fix the font by checking the box in the inspector panel).

**Comment by j-bresson** [comment]
Can you let me know if it looks better with this last commit ?

**Comment by geofholbrook** [comment]
Ok, I see now that changing the preference doesn't change the font size for existing comments. I think that is appropriate, to answer your question above; a change to the preference setting should only change comments created thereafter. 
   Mostly the patches looked OK to me, but I did have to change the width of most of the titles, hence the new commit.
   By the way yes, I did a reset --hard and everything is fine now, no conflicts!

**Comment by j-bresson** [comment]
> a change to the preference setting should only change comments created thereafter.

This is something to think about globally, for instance, if we think about connections (straight/curved) : you might be interested to apply a change globally (same for rounded corners, and other graphical attributes). Font is a little bit more tricky because it interferes with sizes.

**Comment by j-bresson** [comment]
Also, there's the isse with different dpi screens (and Mac vs. Windows), that the "global setting" partially solves...

**Comment by geofholbrook** [comment]
OK, but surely we don't want the layout of the help-patches (or any other patch made by someone else) to be all broken and messed up because of the user's global setting? In fact I kind of feel similarly about connections (I can make a patch that is very readable with curved connections but if one switches to straight it looks like heck). 

But I see now, your commit "Set fixed comment fonts" just locks the fonts for the help patches. How did you do that, is there access in the interface for that or did you edit the files manually?

**Comment by j-bresson** [comment]
> How did you do that

I edited the files, checking the box in front of the "Comment font" property. 

Given the current behaviour of this, maybe a new patch-editing command coudl be "lock current appearance", and that woudl do it automatically (also for box attributes, connections, etc.) ...

**Comment by geofholbrook** [comment]
OK, I see. I was going to suggest pretty much that, the ability to lock the
appearance. In the case of comment fonts, that would save the task of
checking the box for every comment

**Comment by j-bresson** [comment]
Anothe "trade-off" would be that this 3locked" state of the properties just be the default (and you can uncheck the box to just follow or return to the preference value).

**Pull request merged**
