### PR TITLE
Tty slime comm

### PR DESCRIPTION
**Pull request by andersvi**
enable support for using om# with slime in emacs

om# needs it's own slime, because compile-file is missing in releases

as well, a start-tty-listener (from the prefs) to have a repl running in the shell where om# was started.

With these additions, the current preferences (in the "general" tab) gets quite messy -> tidy, find better wording, documentation

### CODE REVIEW

**Comment by andersvi** [comment]
@j-bresson , I remember you weren't too happy about including submodules, so suggest just having this in here until things are ready for merge.  The reason is that latest release of slime won't work without local hack anyway.

**Comment by j-bresson** [comment]
I guess it makes sense to include a submodule here. However I would maybe first fork slime in the organization repo, then use it as submodule.

**Comment by j-bresson** [comment]
-- I'm doing it now and will update the branch before merge

**Comment by andersvi** [comment]
I'd say we wait a bit with merging.  There are some issues how to tune debugging, as well as the rather confusing options in the :general prefs.

**Comment by andersvi** [comment]
@j-bresson - suggest to pull in this now.  Things work seemingly, potentially fine-tune further during actual usage.

**Comment by j-bresson** [comment]
> suggest to pull in this now.

`om-preferences.lisp` is displayed in conflict. are you taking care of it ?

**Comment by andersvi** [comment]
Fine. I'll resolve the conflict and merge into origin/master then.

**Comment by andersvi** [comment]
Says 'unmerged commits', but everything in tty-slime-comm was rebased on master and pushed to origin/master.

**Pull request closed without merging**
